[package]
name = "fn-tracer"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[features]
fn_trace = []

[dependencies]
syn = { version = "2.0", features = ["full", "parsing"] }
quote = "1.0"
proc-macro2 = "1.0.95"