[package]
name = "file_encryptor"
version = "0.1.0"
edition = "2024"

[dependencies]
local_utils = {path = "../local_utils", features = ["test_utils"]}
clap = { version = "4.5.37", features = ["derive"] }
tar = "0.4.44"