[package]
name = "file_encryptor"
version = "0.1.0"
edition = "2024"

[dependencies]
rustware = {path = "../../rustware", features = ["test_utils"]}
clap = { version = "4.5.37", features = ["derive"] }
tempfile = "3.20.0"